name: Act on release created

on:
  release:
    types: [created]

jobs:
  build:
    name: Clone all latest release from all repo
    environment: build_environment
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v3
        with:
          repository: venkatkasi/repo2
          path: repo2
          
     - uses: actions/checkout@v3
        with:
          repository: venkatkasi/repo3
          path: repo3
        
     - uses: actions/checkout@v3
         with:
           repository: venkatkasi/repo4
           path: repo
